codecov:
  notify:
    require_ci_to_pass: yes

ignore:
  - "repository/impl/.*"
  - "repository/impl/*"
  - "repository/impl"
  - "repository/util/pod-util.ts"
  - "src/service/*base*"
  - "test.ts"
  - "src/cli/.*"
  - "src/cli"
  - "src/cli/*"
  - "dist/.*"
  - "dist/*"
  - "dist"

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
