language: node_js
sudo: false # faster builds
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
  - npm install -g yo
  - npm install -g @inrupt/generator-solid-angular
  - npm install
  - npm audit fix --force
script: 
  - ng build --prod
after_success:
  - bash <(curl -s https://codecov.io/bash)
