language: node_js
sudo: false # faster builds
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
  - "sed -i 's/node: false/node: {stream: false, crypto: false}/g' /home/travis/build/Arquisoft/dechat_es2b/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js"
script:
  - ng build --prod
after_success:
  - ng test --watch=false
  - cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
