language: node_js
sudo: false # faster builds
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
  - "sed -i 's/node: false/node: {stream: true, crypto: true}/g' node_modules/@angular-devkit/build-angular/src/angular-cli.bat-files/models/webpack-configs/browser.js"
script:
  - ng build --prod
after_success:
  - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - bash <(curl -s https://codecov.io/bash)
