= dechat_es2b

image:https://travis-ci.org/Arquisoft/dechat_es2b.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es2b"]
image:https://codecov.io/gh/Arquisoft/dechat_es2b/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_es2b"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_es2b/badge.svg["Coverage",link="https://coveralls.io/github/Arquisoft/dechat_es2b"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es2b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es2b&utm_campaign=Badge_Grade"]


== Introduction

Como alumnos de la asignatura de https://github.com/Arquisoft/[Arquitectura del Software de la Universidad de Oviedo], se nos encargó, como trabajo de clase, desarrollar un chat descentralizado, utilizando https://solid.inrupt.com[SOLID], la nueva tecnología que nos presenta https://twitter.com/timberners_lee?lang=es[Tim Berners Lee] para descentralizar la Web.


== Compile and run

The skeleton project is a simple https://angular.io[Angular] application which can be run as:
----
 ng serve
----

Once executed, the application should be available at: http://127.0.0.1:4200


== Authors and Meetings

The members that we develop in this repo are:

* Enol García González
* Andrés Casillas
* Tomás Argüelles

We make a meeting at least once a week. Every time we meet, we prepare a report with everything that was discussed. All the information can be found in our https://github.com/Arquisoft/dechat_es2b/wiki/Meeting-Book[English meeting book] and our https://github.com/Arquisoft/dechat_es2b/wiki/Libro-de-reuniones[Spanish meeting book]