= dechat_es2b

image:https://travis-ci.org/Arquisoft/dechat_es2b.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es2b"]
image:https://codecov.io/gh/Arquisoft/dechat_es2b/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_es2b"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es2b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es2b&utm_campaign=Badge_Grade"]


== Introduction

As students of the https://github.com/Arquisoft/[Software Architecture course at the University of Oviedo], we were entrusted to develop a decentralized chat as classwork. This chat must be developed using https://solid.inrupt.com[SOLID], the new technology that https://twitter.com/timberners_lee[Tim Berners Lee] presents to us to decentralize the Social Networks in the Web.


== Compile and run

The skeleton project is a simple https://angular.io[Angular] application which can be executed after you run `npm install` to update the dependencies and you have done one of the followings:

· If you use UNIX: Run `sed -i 's/node: false/node: {stream: true, crypto: true}/g' node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js`

· Go to `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js` and use `node: {crypto: true, stream: true}` at the end of the file replacing `node: false`.

Finally run:
----
 ng serve
----

Once executed, the application should be available at: http://localhost:4200/


== Command Line Interface


=== Requirements

In order to use the cli version you have two do next things:

* You have to be installed NodeJS
* OpenSSL must be in your computed and configured in the system path


=== Usage

You can compile the project to execute it into command line. The command line application can be compiled by executing:
----
 tsc -p src/cli --outDir dist/cli
----

And then, it can be executed using:
----
node dist/cli/cli/cli.js
----


== Authors and Meetings

The members that we develop in this repo are:

* Enol García González
* Andrés Casillas
* Tomás Argüelles

We make a meeting at least once a week. Every time we meet, we prepare a report with everything that was discussed. All the information can be found in our https://github.com/Arquisoft/dechat_es2b/wiki/Meeting-Book[English meeting book] and our https://github.com/Arquisoft/dechat_es2b/wiki/Libro-de-reuniones[Spanish meeting book]
